name: hancockjourney
favicon: null
layout_spectrum: 0.84253
typography_spectrum: 0.26646
title: The Hancock Journey
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b8c0a8'
    - '#1e2658'
    - '#f6f2ba'
    - '#9e787f'
    - '#7d1e51'
  brandStrength: 0.3440466255415231
  lightness: 0.9192928844131529
  saturation: 0.11774616478942335
  rhythmicContrast: 0.6611740947701037
purpose: []
